site_name: LangChain Russian Docs
site_url: https://llmdev.ru/

theme:
  name: material
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  features:
    - navigation.instant
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - –ì–ª–∞–≤–Ω–∞—è: index.md
  - –û—Å–Ω–æ–≤—ã:
      - basics/introduction.md
  - –û—Å–Ω–æ–≤–Ω—ã–µ –∫–æ–º–ø–æ–Ω–µ–Ω—Ç—ã:
      - core_components/agents.md
      - core_components/tools.md
  - –ö–æ–Ω—Ü–µ–ø—Ü–∏–∏:
      - concepts/chat-models.md
      - concepts/context-engineering-in-agents.md
  - –ú–æ–¥—É–ª–∏:
      - 'Llama.cpp': modules/llamacpp.md
      - 'Embedding models': modules/text-embedding.md
      - modules/chroma.md
      - modules/qdrant.md
      - modules/text-splitters.md
      - modules/splitting-code.md
      - modules/retrieval.md
  - –ü—Ä–∞–∫—Ç–∏—á–µ—Å–∫–∏–µ –∫—É—Ä—Å—ã:
      - tutorials/llm-chain.md
      - tutorials/chatbot.md
      - tutorials/rag_agents.md
      - tutorials/model-context-protocol-mcp.md
  - –ò–Ω—Ç–µ–≥—Ä–∞—Ü–∏–∏:
      - integrations/openai.md
  - üêç Pomodoro ‚è≥: pomodoro.html

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - offline
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      enable_creation_date: false

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/Aleks3ds

extra_javascript:
  - js/save_scroll.js
